In [1]:
import numpy as np

In [8]:
arr=np.array([2,3,4,5])

In [9]:
arr*2

array([ 4,  6,  8, 10])

In [10]:
arr**2+5

array([ 9, 14, 21, 30], dtype=int32)

In [11]:
arr/2

array([1. , 1.5, 2. , 2.5])

In [12]:
arr/0  # this will give infinity not error

C:\Users\ZEERAK~1\AppData\Local\Temp/ipykernel_2104/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([inf, inf, inf, inf])

In [13]:
arr

array([2, 3, 4, 5])

In [14]:
# operations on two or more array.

In [16]:
import numpy as np

In [17]:
ar1=np.array([5,10,15,20])
ar2=np.array([1,2,3,4])
ar3=np.array([5,6,7,8])

In [18]:
ar1+ar2+ar3


array([11, 18, 25, 32])

In [19]:
ar1*ar2+ar3

array([10, 26, 52, 88])

In [20]:
ar1+ar2-ar3*ar1

array([ -19,  -48,  -87, -136])

In [23]:
ar1/ar2+ar3

array([10., 11., 12., 13.])

In [24]:
# now we can perform operation on matrix

In [25]:
np.random.seed(123)
matrix1=np.random.randint(1,11,9).reshape(3,3)
matrix2=np.random.randint(12,23,9).reshape(3,3)

In [26]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [27]:
matrix2

array([[13, 21, 12],
       [12, 21, 15],
       [16, 12, 12]])

In [28]:
matrix1*matrix2 # simple product

array([[ 39,  63,  84],
       [ 24,  84, 150],
       [112,  24,  12]])

In [29]:
matrix1**matrix2

array([[    1594323,  1870418611,   956385313],
       [       4096,           0, -1530494976],
       [-1526366847,        4096,           1]], dtype=int32)

In [31]:
matrix2-matrix1

array([[10, 18,  5],
       [10, 17,  5],
       [ 9, 10, 11]])

In [32]:
matrix2/matrix1


array([[ 4.33333333,  7.        ,  1.71428571],
       [ 6.        ,  5.25      ,  1.5       ],
       [ 2.28571429,  6.        , 12.        ]])

In [33]:
matrix1.dot(matrix2) # ist row .ist column+ist row.second column etc....

array([[187, 210, 165],
       [234, 246, 204],
       [131, 201, 126]])