In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,4,5,8,9,10,15])

In [3]:
arr

array([ 1,  2,  4,  5,  8,  9, 10, 15])

In [4]:
arr>5

array([False, False, False, False,  True,  True,  True,  True])

In [8]:
mark=arr>5

In [10]:
arr[mark]

array([ 8,  9, 10, 15])

In [12]:
arr[arr<5]

array([1, 2, 4])

In [13]:
arr[arr%2==0]

array([ 2,  4,  8, 10])

In [14]:
arr[arr%2==1]

array([ 1,  5,  9, 15])

In [15]:
arr

array([ 1,  2,  4,  5,  8,  9, 10, 15])

In [17]:
arr[arr==10]

array([10])