In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7])

In [3]:
sliced_arr=arr[0:6].copy()

In [4]:
sliced_arr

array([1, 2, 3, 4, 5, 6])

In [7]:
sliced_arr[0:3]=0

In [8]:
sliced_arr

array([0, 0, 0, 4, 5, 6])

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
sliced_arr

array([0, 0, 0, 4, 5, 6])