In [27]:
import numpy as np

In [28]:
arr=np.array([1,2,3,4,5,6])

In [29]:
arr

array([1, 2, 3, 4, 5, 6])

In [31]:
arr1=np.arange(20,41)

In [32]:
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [35]:
fives=np.ones(10)*5

In [36]:
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [39]:
arr2=np.random.randint(1,50,24).reshape(3,4,2)

In [40]:
arr2

array([[[18,  3],
        [48, 49],
        [ 3,  2],
        [49, 36]],

       [[21, 37],
        [ 7, 24],
        [23,  4],
        [46,  2]],

       [[42, 44],
        [ 1, 22],
        [47, 35],
        [42, 13]]])

In [42]:
arr3=np.random.rand(4,5)

In [52]:
arr3

array([[0.96807003, 0.06796204, 0.87858809, 0.78410735, 0.41062011],
       [0.17305671, 0.74197864, 0.73492002, 0.66371046, 0.31202094],
       [0.45441383, 0.01231275, 0.33792398, 0.48750261, 0.25769174],
       [0.56342572, 0.26771345, 0.6480807 , 0.5793309 , 0.86396581]])

In [58]:
np.random.seed(123)
arr4=np.random.randint(1,50,20)
arr4[arr4%2==0]=-1
arr4

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

In [59]:
matrix=np.array([[5,10,15,20,25],
                [30,35,40,45,50],
                [55,60,65,70,75],
                [80,85,90,95,100]] )
matrix

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [66]:
matrix[1:3 ,0:3]

array([[30, 35, 40],
       [55, 60, 65]])

In [67]:
arr5=np.array([1,2,3,4])
arr6=np.array([5,6,7,8])
np.hstack((arr5,arr6))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
np.vstack((arr5,arr6))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
matrix1=np.random.randint(1,30,9).reshape(3,3)
matrix2=np.random.randint(15,35,9).reshape(3,3)
matrix1

array([[13,  9,  4],
       [11,  6,  1],
       [12,  3, 27]])

In [72]:
matrix2

array([[25, 28, 33],
       [19, 30, 26],
       [27, 21, 28]])

In [73]:
np.hstack((matrix1,matrix2))

array([[13,  9,  4, 25, 28, 33],
       [11,  6,  1, 19, 30, 26],
       [12,  3, 27, 27, 21, 28]])

In [74]:
np.vstack((matrix1,matrix2))

array([[13,  9,  4],
       [11,  6,  1],
       [12,  3, 27],
       [25, 28, 33],
       [19, 30, 26],
       [27, 21, 28]])