In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,35,6,7,8])

In [4]:
arr[4]

6

In [5]:
arr[0]

1

In [6]:
arr[-1]

8

In [7]:
arr[-3]

6

In [8]:
arr[-7]

1

In [10]:
arr[:6]

array([ 1,  2,  3, 35,  6,  7])

In [11]:
arr[: : -1]

array([ 8,  7,  6, 35,  3,  2,  1])

In [12]:
arr[0:5:2]

array([1, 3, 6])

In [16]:
arr[-5:]

array([ 3, 35,  6,  7,  8])