In [12]:
import numpy as np

In [15]:
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [16]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
matrix[0][3] # double bracket notation indexing

4

In [18]:
matrix[2][1]

10

In [19]:
matrix[2,2] # single bracket indexing notation

11

In [20]:
matrix[1,3]

8

In [22]:
matrix[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [25]:
matrix[0:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [29]:
np.random.seed(123)

In [30]:
matrix1=np.random.randint(1,60,20).reshape(5,4)

In [31]:
matrix1

array([[46,  3, 29, 35],
       [39, 18, 20, 43],
       [58, 23, 34, 33],
       [50, 48, 10, 33],
       [47, 33, 48, 26]])

In [37]:
matrix1[1:3,1:4]  # single bracket notation slicing of 2d array.

array([[18, 20, 43],
       [23, 34, 33]])