In [5]:
import numpy as np

In [7]:
np.random.seed(123)
matrix=np.random.randint(1,12,9).reshape(3,3)

In [8]:
matrix

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [9]:
np.min(matrix)

2

In [10]:
np.max(matrix)

11

In [11]:
#rows=1,column=0

In [12]:
np.min(matrix,axis=1) # to find minimum element in rows

array([3, 2, 2])

In [13]:
np.min(matrix,axis=0)

array([2, 3, 2])

In [14]:
np.sum(matrix,axis=1)

array([13, 17, 19])

In [15]:
np.prod(matrix,axis=0)

array([ 60,  84, 154])

In [16]:
np.cumsum(matrix) #cumulative sum, is a sequence of partial sums of a given data set. 

array([ 3,  6, 13, 15, 19, 30, 40, 47, 49], dtype=int32)

In [17]:
np.cumsum(matrix,axis=1)

array([[ 3,  6, 13],
       [ 2,  6, 17],
       [10, 17, 19]], dtype=int32)

In [18]:
np.prod(matrix)

776160