In [1]:
import numpy as np

In [2]:
np.random.seed(123)
arr=np.random.randint(1,12,9)
arr

array([ 3,  3,  7,  2,  4, 11, 10,  7,  2])

In [3]:
np.random.shuffle(arr)

In [4]:
arr

array([ 2, 11,  4,  7,  2,  7, 10,  3,  3])

In [5]:
np.unique(arr)

array([ 2,  3,  4,  7, 10, 11])

In [6]:
np.unique(arr).size

6

In [7]:
np.unique(arr,return_index=True, return_counts=True)

(array([ 2,  3,  4,  7, 10, 11]),
 array([0, 7, 2, 3, 6, 1], dtype=int64),
 array([2, 2, 1, 2, 1, 1], dtype=int64))