In [1]:
import numpy as np


In [2]:
arr=np.zeros((2,3))

In [3]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr=np.ones((2,2))

In [7]:
arr

array([[1., 1.],
       [1., 1.]])

In [9]:
matrix=np.eye((4))

In [10]:
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
arr=np.eye((3))

In [14]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
matrix=np.diag([3,4,5,6,7])

In [32]:
matrix

array([[3, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 7]])

In [33]:
rand_num=np.random.randint(1,80,10)

In [34]:
rand_num

array([71,  6, 62, 12,  4, 74, 62, 28, 63, 24])

In [37]:
rand_numb=np.random.rand(2) # this will print random numnber b/w 0 and 1

In [38]:
rand_numb

array([0.83871752, 0.13516956])

In [43]:
rand_num1=np.random.randn(50) # tomprint meanm of these numbers and the  mean must be near to 1.

In [44]:
rand_num1

array([ 0.61740053,  0.21082779,  0.38566558,  0.16472528, -0.4656126 ,
        0.961179  ,  0.14096772, -0.28079814, -0.09190932,  0.27964081,
       -0.4487218 ,  0.18520372,  0.23424593,  0.7537241 , -0.21176054,
       -0.25366451, -0.30276677,  0.41709749,  1.58190499,  0.63725399,
        0.53478725,  0.51634266, -1.50108088,  0.20576417,  0.97066727,
        0.85554905,  0.13756964, -1.45977264,  0.23125824, -1.17595921,
        1.75414931,  1.39001503, -0.47363478, -0.36097198,  0.84392256,
        0.6881178 ,  1.48155457, -0.35440537,  0.53845849, -0.31930624,
        0.19199384, -0.52090747, -0.87759798,  1.20184341, -0.41032108,
       -1.10503192, -0.55197233, -0.48071857, -1.484217  , -0.65535269])

In [54]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
arr.reshape(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
ar=np.random.randint(10,100,25)

In [61]:
ar

array([94, 92, 20, 60, 38, 32, 43, 46, 59, 72, 18, 87, 74, 10, 37, 72, 16,
       13, 92, 48, 21, 94, 52, 51, 92])

In [62]:
ar.reshape(5,5) # 2d array

array([[94, 92, 20, 60, 38],
       [32, 43, 46, 59, 72],
       [18, 87, 74, 10, 37],
       [72, 16, 13, 92, 48],
       [21, 94, 52, 51, 92]])

In [67]:
ar1=np.random.randint(10,100,24)

In [68]:
ar1

array([46, 74, 93, 84, 69, 61, 75, 60, 14, 71, 80, 93, 54, 10, 62, 23, 15,
       65, 58, 56, 79, 55, 98, 28])

In [70]:
ar1.reshape(2,2,6)

array([[[46, 74, 93, 84, 69, 61],
        [75, 60, 14, 71, 80, 93]],

       [[54, 10, 62, 23, 15, 65],
        [58, 56, 79, 55, 98, 28]]])

In [74]:
arr1=np.random.randint(10,50,16)