In [1]:
import numpy as np

In [2]:
arr=np.array([2,80,5,7,90,4])

In [3]:
arr

array([ 2, 80,  5,  7, 90,  4])

In [4]:
np.min(arr)  # print minimum element in array

2

In [5]:
np.max(arr) # show maximum element of array

90

In [6]:
np.argmin(arr) # show position of min element

0

In [8]:
np.argmax(arr)# show position of max element

4

In [9]:
np.sum(arr) # print sum of the All element of the array.

188

In [10]:
np.sqrt(arr) # print square root of the all element 

array([1.41421356, 8.94427191, 2.23606798, 2.64575131, 9.48683298,
       2.        ])

In [11]:
np.sin(arr) # value of sin

array([ 0.90929743, -0.99388865, -0.95892427,  0.6569866 ,  0.89399666,
       -0.7568025 ])

In [12]:
np.cos(arr)# value of cos

array([-0.41614684, -0.11038724,  0.28366219,  0.75390225, -0.44807362,
       -0.65364362])

In [13]:
np.exp(arr)

array([7.38905610e+00, 5.54062238e+34, 1.48413159e+02, 1.09663316e+03,
       1.22040329e+39, 5.45981500e+01])

In [17]:
arr1=np.array([1,1,0,1,0,1,1,0],dtype='bool') # to print boolen value insted of 1 and 0

In [18]:
arr1

array([ True,  True, False,  True, False,  True,  True, False])

In [21]:
for i in arr1:
    print(i,end=' ')  # use to itterate the all element of the second array.

True True False True False True True False 

In [22]:
np.linspace(1,11,9)

array([ 1.  ,  2.25,  3.5 ,  4.75,  6.  ,  7.25,  8.5 ,  9.75, 11.  ])