In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,4,3,5,5])

In [33]:
sliced_array=arr[0:5]

In [34]:
sliced_array

array([0, 0, 0, 0, 0])

In [17]:
sliced_array[:]=0

In [18]:
sliced_array

array([0, 0, 0, 0, 0])

In [20]:
arr

array([0, 0, 0, 0, 0, 5])

In [23]:
sliced_array[0:5]=[1,2,4,3,5]

In [24]:
sliced_array

array([1, 2, 4, 3, 5])

In [31]:
sliced_array1=arr[0:5].copy() # to copy element from the array

In [32]:
sliced_array1

array([0, 0, 0, 0, 0])